Added reportlab requirement
reportlab has to be 3.4.0 or less. Higher version have conflict.

Conflict creates error:

AttributeError: RotatedPara instance has no attribute 'blPara'